### ISSUE TITLE
Package website link broken

### ISSUE THREAD

**Issue by stineb** [khufkens/MODISTools#16]
Hey K, the link to the website https://khufkens.github.io/MODISTools/ is no longer active. Is there a new site for this?

**Comment by khufkens** [comment]
Thanks for noticing this. You can access the website here:
https://ropensci.github.io/MODISTools/

I forwarded this to the @karthik who took care of the transfer of the project.
https://github.com/ropensci/software-review/issues/246

**Comment by karthik** [comment]
Fixed!
