### ISSUE TITLE
Cannot get data by using this library

### ISSUE THREAD

**Issue by YuanGao-NAU** [khufkens/MODISTools#17]
Hi, I have problems by using this library. About one month ago, I can use this lib to get data, but today when I use this lib, I cannot get data, even use the example in the document. The function mt_products() and mt_bands() are ok, but the mt_subset() is not. I used the example in the document:
`
subset <- mt_subset(product = "MOD11A2",
lat = 40,
lon = -110,
band = "LST_Day_1km",
start = "2004-01-01",
end = "2004-03-31",
progress = FALSE)
`
I cannot get the response data. Can you help? Thanks.

**Comment by khufkens** [comment]
The demo calls in the worked examples didn't work for me yesterday, but do right now. 

As I suspected this is a server issue, not a package issue. In short, if data calls time-out the server is just too slow (either congested or they are doing maintenance on the data part - assuming that the meta-data calls `mt_bands()` and `mt_products()` are actually different dbases).

So if `mt_bands()` works, but `mt_subset()` doesn't give it some time. You might benefit from scheduling downloads during the night, or weekends.

**Comment by YuanGao-NAU** [comment]
Ok, thank you. This lib helps me a lot. Excellent job!



---Original---
