### ISSUE TITLE
progress = TRUE not showing progress bar

### ISSUE THREAD

**Issue by RussellGrayxd** [khufkens/MODISTools#19]
I have been using the package over the last week without much issue. However, after running a few queries today, the progress = TRUE argument in the mt_subset() function appears not to function. I get the red "loading" button, but no progress bar in the console.

Any idea what could be going on?

**Comment by khufkens** [comment]
The API can be slow. For large queries try to run the code on US nights or
over the weekend.

**Comment by RussellGrayxd** [comment]
I'm not sure that its the API, I'm querying in the daytime in Vietnam, which is night time in the US. I've been trying to query a simple landcover raster for a single year for about 8 hours now. it just continually loads until I stop it. The same code used about a week ago said "downloading chunks" and showed a progress bar. 

Landcov <- mt_subset(product = "MCD12Q1",                lat = mlat,                lon = mlong,                band = "LC_Type1",                start = "01-01-2001",                km_lr = 10,                km_ab = 10,                site_name = "1",                internal = TRUE,                progress = TRUE)
This is the code I'm using. 




-Russell Gray
    On Thursday, December 19, 2019, 02:49:19 p.m. GMT+7, Koen Hufkens <notifications@github.com> wrote:  
 
 The API can be slow. For large queries try to run the code on US nights or
over the weekend.

**Comment by RussellGrayxd** [comment]
Sorry, that last one was code from another rscript
Landcov <- mt_subset(product = "MCD12Q1",                lat = 12.48036,                lon = 8.486359,                band = "LC_Type1",                start = "01-01-2001",                end = "01-01-2001",                km_lr = 10,                km_ab = 10,                site_name = "1",                internal = TRUE,                progress = TRUE)

This is the code I'm using
    On Thursday, December 19, 2019, 03:03:06 p.m. GMT+7, Russell Gray <russell_graypt@yahoo.com> wrote:  
 
  I'm not sure that its the API, I'm querying in the daytime in Vietnam, which is night time in the US. I've been trying to query a simple landcover raster for a single year for about 8 hours now. it just continually loads until I stop it. The same code used about a week ago said "downloading chunks" and showed a progress bar. 

Landcov <- mt_subset(product = "MCD12Q1",                lat = mlat,                lon = mlong,                band = "LC_Type1",                start = "01-01-2001",                km_lr = 10,                km_ab = 10,                site_name = "1",                internal = TRUE,                progress = TRUE)
This is the code I'm using. 




-Russell Gray
    On Thursday, December 19, 2019, 02:49:19 p.m. GMT+7, Koen Hufkens <notifications@github.com> wrote:  
 
 The API can be slow. For large queries try to run the code on US nights or
over the weekend.

**Comment by khufkens** [comment]
The date should read 2001-01-01, I'll fix this in the documentation as this
isn't clear.
