### ISSUE TITLE
Check formatting of dates

### ISSUE THREAD

**Issue by khufkens** [khufkens/MODISTools#20]
Check the format of the dates (YYYY-MM-DD) provided in a query. The API call will stall when faulty dates are provided.

**Comment by makovz** [comment]
since few days ago, I've been getting various errors while downloading data using mt_subset function. Any known current server malfunction? thanks

**Comment by khufkens** [comment]
Don't see any changes on the ORNL end on their API so I fear it is a server issue. Often the custom queries get lower priority to the site based data (which is pre-loaded). I would give it some time still, often the service rebounds.

**Comment by khufkens** [comment]
I've done some test, thinking it was a rate limiting issue. However, even only querying 3 or so dates of data will fail with odd errors. Some of them returning an http 500 statement (i.e. internal server error).

**Comment by makovz** [comment]
thanks, same issue here

**Comment by khufkens** [comment]
ORNL filed a ticket and got back to me with this, basically what I expected.

```
We performed a hardware upgrade on Monday 2/17 that has caused the difficulties that you are currently experiencing.
All available resources are working to resolve these issues as soon as possible.

I'll drop you a line as soon as we resolve this problem.
```

**Comment by khufkens** [comment]
Server is back online.
