### ISSUE TITLE
There is no MODISSummaries() to use QA band

### ISSUE THREAD

**Issue by Yinshao-lzu** [khufkens/MODISTools#25]
Hello, I want to use QA band to constraint pixel value. But  no MODISSummaries() was found in MODISTools package, that was described in the paper of " MODISTools -- downloading and processing MODIS remotely sensed data in R".  In addition, the mt_batch_subset() can not download two bands at the same time.
![QQ截图20200909100301](https://user-images.githubusercontent.com/56902640/92545867-ad477380-f283-11ea-8969-0dc2d9e232e9.jpg)

**Comment by khufkens** [comment]
This is a refactored version of the original, as the original author did not want to maintain the codebase. You will have to write your own screening code.

Tidy data is returned and can easily be pivoted into a format which allows easy screening. Look at `left_join()` and `pivot_wider()` of dplyr to accomplish this.
