### ISSUE TITLE
Error in open.connection when running mt_subset

### ISSUE THREAD

**Issue by rsmiller74** [khufkens/MODISTools#27]
Error occurs when running code from documentation.  Happens in both development version and cran version.  

> subset <- mt_subset(product = "MOD11A2",
+                     lat = 40,
+                     lon = -110,
+                     band = "LST_Day_1km",
+                     start = "2004-01-01",
+                     end = "2004-03-31",
+                     progress = FALSE)
Error in open.connection(con, "rb") : HTTP error 500.
Error: $ operator is invalid for atomic vectors

**Comment by yiluansong** [comment]
I had the exact same issue.

**Comment by rsmiller74** [comment]
anyone know how to fix this issue?  current R version is...

> R.Version()
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.2"

$year
[1] "2020"

$month
[1] "06"

$day
[1] "22"

$`svn rev`
[1] "78730"

$language
[1] "R"

$version.string
[1] "R version 4.0.2 (2020-06-22)"

$nickname
[1] "Taking Off Again"

**Comment by rsmiller74** [comment]
anyone know how to fix this issue?  current R version is...

> R.Version()
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "0.2"

$year
[1] "2020"

$month
[1] "06"

$day
[1] "22"

$`svn rev`
[1] "78730"

$language
[1] "R"

$version.string
[1] "R version 4.0.2 (2020-06-22)"

$nickname
[1] "Taking Off Again"

**Comment by stineb** [comment]
Same error when running `mt_products()`:

```
Error in open.connection(con, "rb") : HTTP error 500.
Error in try(jsonlite::fromJSON(url))$products : 
  $ operator is invalid for atomic vectors
```

**Comment by khufkens** [comment]
This indicates that the url structure has changed. I'm on holiday so check
the ornl API docs and correct the endpoint url or data structure and push
the changes. Also check if the server isn't down, which happens and can
give the same issues.

**Comment by stineb** [comment]
Thanks Koen! I checked URL `https://modis.ornl.gov/rst/ui/#!/products/get_products` using my browser and got the same error:
```
{
  "type": "about:blank",
  "title": "Internal Server Error",
  "detail": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500
}
```
I guess this means that the URL has not changed but the server is not responding? 

It might be worth including an abort statement with a more informative message through the MODISTools package if that happens. 

Enjoy your holidays!

**Comment by khufkens** [comment]
Thanks @stineb 

Will close this report, opened a new enhancement ticket here https://github.com/ropensci/MODISTools/issues/28
