### ISSUE TITLE
Reference MODISTools version described in Tuck et al. (2014) paper

### ISSUE THREAD

**Issue by peterdesmet** [khufkens/MODISTools#29]
The [Tuck et al. (2014) paper](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.1273) that describes the MODISTools package, references functions that are no longer available or renamed in the current version of the package. Would it be possible to mention this in the README for users that discover the package via the paper? For example:

> Tuck et al. (2014). [MODISTools - downloading and processing MODIS remotely sensed data in R Ecology &
Evolution](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.1273), 4(24), 4658 - 4668.
> 
> The paper above describes version x of the package (available at ...). Since then, the maintenance of the package has been transferred and the package refactored. Use `function()` for `MODISSubsets()`, ...

Note: Old releases seem to be available at https://cran.r-project.org/src/contrib/Archive/MODISTools/ but not 0.94.3 that is listed in one of the scripts associated with the paper:

```R
sessionInfo()
# MODISTools_0.94.3
```

**Comment by khufkens** [comment]
Hi Peter,

I'll adjust the README. The plan was to rewrite a paper similar to Tuck et al. combined with some python tools written by other collaborators. Alas, these things aren't a priority and this hasn't happened yet, hence the faulty reference.

Cheers,
K

**Comment by khufkens** [comment]
Fixed per https://github.com/ropensci/MODISTools/commit/eafbc23715e147d0aca8087d3e9c721d10cb17c6

**Comment by peterdesmet** [comment]
Thanks! I noticed the build failing (https://travis-ci.org/github/ropensci/MODISTools) so it is not yet available on the website?

**Comment by peterdesmet** [comment]
Build is now running again I see and the updated description is in [`README.Rmd` in master](https://github.com/ropensci/MODISTools/blob/master/README.Rmd). :clap:

I noticed however that the [website is still at v1.1.1](https://docs.ropensci.org/MODISTools/) not the v1.5.1 in `docs/`  (which includes the change). The `README.Rmd` in master is also not knitted from `README.md` (last change was 17 months ago). Is this on purpose (keeping website at v1.1.1)?

**Comment by khufkens** [comment]
v1.1.1 is the CRAN release, not the current version on the master branch. I also don't increment DESCRIPTION details with every small issue.
