### ISSUE TITLE
URL issue

### ISSUE THREAD

**Issue by DongchenZ** [khufkens/MODISTools#36]
Hi!
When I am trying to download MODIS lai data from MODISTools and it seems the URL is broken and I got the following errors when I just use a build-in function:
```
MODISTools::mt_products()
Error in open.connection(con, "rb") : HTTP error 500.
Error in try(jsonlite::fromJSON(url))$products : 
  $ operator is invalid for atomic vectors
```
could you help me with that?
Best wishes,
Dongchen

**Comment by khufkens** [comment]
There is maintenance on the ORNL server, check back later
