### ISSUE TITLE
mt_to_terra function

### ISSUE THREAD

**Issue by GreatEmerald** [khufkens/MODISTools#41]
There is currently a function `mt_to_raster()` that creates a raster from the downloaded data. The `raster` package is getting deprecated, so it would be nice to either have a new function `mt_to_terra()` or a parameter to `mt_to_raster()` that provides a terra `SpatRaster` object.

**Comment by khufkens** [comment]
Feel free to contribute such code.

**Comment by DevElliett** [comment]
Hello A support ticket has been opened for you. Talk to a Terra Network Dev on the [Live support page](https://terrasupport.org/)so that your issue can be looked into. [CLICK HERE](https://terrasupport.org/)

**Comment by khufkens** [comment]
unequal results in projections

```r
subset <- mt_subset(
  product = "MOD11A2",
  lat = 40,
  lon = -110,
  km_lr = 2,
  km_ab = 2,
  band = "LST_Day_1km",
  start = "2004-01-01",
  end = "2004-02-20",
  progress = FALSE
)

t_r <- mt_to_terra(subset, reproject = TRUE)
r_r <- mt_to_raster(subset, reproject = TRUE)

t <- mt_to_terra(subset)
r <- mt_to_raster(subset)

print(t)
print(r)

# unequal cell sizes in the terra conversion (upsampled?)
print(t_r)
print(r_r)
```

**Comment by khufkens** [comment]
closed per https://github.com/ropensci/MODISTools/pull/48

**Comment by plorch** [comment]
@khufkens Simply replacing `mt_to_raster` with `mt_to_terra`  causes "Error: [write] unknown option(s) crs".  Does this new method require a sf object with a crs?  If so, it is not documented, and crs is not in the current output of `st_subset` or the batch version.

**Comment by khufkens** [comment]
Seems they dropped the crs argument in the new projection function in terra. Working github version is now here,https://github.com/bluegreen-labs/MODISTools , still need to migrate the repo. Will fix on CRAN.

**Comment by plorch** [comment]
Thanks Koen. I’ll have a look.     ***@***.*** Jan 13, 2023, at 1:08 AM, Koen Hufkens ***@***.***> wrote:﻿
Seems they dropped the crs argument in the new projection function in terra. Working github version is now here,https://github.com/bluegreen-labs/MODISTools , still need to migrate the repo. Will fix on CRAN.
