### ISSUE TITLE
HTTP Error 500 with mt_batch_subset

### ISSUE THREAD

**Issue by sarahjain** [khufkens/MODISTools#44]
Hi, 

I have tried to access mt_batch_subset(), but have been recieving the error message
 **"Error in open.connection(con,'"rb") : HTTP error 500
  Error : $ operator is invalid for atomic vectors"**

The same issue was observed even with mt_dates. 

`df <- data.frame("site_name" = paste("test",1:2))
df$lat <- 40
df$lon <- -110

print(df)

subsets <- mt_batch_subset(df = df,
                        product = "MOD11A2",
                        band = "LST_Day_1km",
                        internal = TRUE,
                        start = "2004-01-01",
                        end = "2004-03-31")`

[Above code snippet from https://www.rdocumentation.org/packages/MODISTools/versions/1.1.1/topics/mt_batch_subset]
Can I please know when this issue will be resolved?

The current version of my R is R 4.1.0 and version of MODISTools is 1.1.1

Thank You.

**Comment by khufkens** [comment]
This is an ORNL issue.

As per earlier issue:
https://github.com/ropensci/MODISTools/issues/43
