### ISSUE TITLE
A little question, thanks for your review

### ISSUE THREAD

**Issue by kangning-97** [khufkens/MODISTools#45]
m <- c(as.numeric(cellsize) * as.numeric(ncols),
         as.numeric(cellsize) * as.numeric(nrows)) * trans +
    c(as.numeric(xllcorner), as.numeric(yllcorner))
  m <- matrix(m, 5, 2, byrow = TRUE)  

         This is an amazing and novel design, while my question is this codes would product the boundary of the total data, and how can we get the specific boundary of each   block (or one little cell).

**Comment by khufkens** [comment]
What is the question here? I don't understand what the goal of the statement is.

**Comment by kangning-97** [comment]
I am very honored to receive your reply. My question is following: I got the NDVI by your package. For each site, I have  25 little pixels. I think  each pixel should be a  square with a specific boundary but not a point, while I can't get the boundary of each pixels. This problem also bothered me when I used R to process AOD data, which each pixels is just a point but not a square with a specific boundary. I am looking forward to your reply. I am a newbie, please don't mind if some of the questions are silly, 
I will try my best to learn from the expert like you. Thank you again, sincerely.

**Comment by khufkens** [comment]
This is discussed here:
https://docs.ropensci.org/MODISTools/articles/modistools-vignette.html#conversion-to-gridded-raster-data
