### ISSUE TITLE
Archiving and/or transfer MODISTools on rOpenSci

### ISSUE THREAD

**Issue by khufkens** [khufkens/MODISTools#50]
Hi @maelle @karthik,

I've decided to hard fork, i.e. reclaim ownership, of {MODISTools} and this for a number or reasons. First and foremost, the platform removes much of the brand recognition I need to keep my consulting business going. Although a great resource for users, I don't think the same can be said for all code developers. 

When promotion, community building, and maintenance remains largely the responsibility of "The Maintainer", while brand recognition and bolstering of a growing ecosystem of packages can only be leveraged at scale by rOpenSci itself I start to question the platform's business model. One can argue that this monetization through (academic) grant seeking, and removes any and all options for small businesses to do so themselves (as money always flows to the top).

I recognize that many contributors are academics for which the "potential" reduced overhead by handing things over to rOpenSci makes sense, as they have other sources of income. However, this equation changes dramatically if part of your income comes from brand recognition of your code work. This dynamic, IMO, does a disservice to small time developers of niche packages once stepping outside the academic sphere.

I'm willing to have an open discussion about this, and technically I would like a clean transfer of the current repository to https://github.com/bluegreen-labs. However, since I don't control this repository I've made sure to hard fork all my latest work beforehand.

I thank the rOpenSci team for early code review, and will consider returning if the platform allows for better visibility and business opportunities for independent consultants who depend on their code for a living.

Kind regards,
Koen

**Comment by karthik** [comment]
Hi Koen,
Thanks very much for honestly sharing your concerns and frustrations. We fully support your decision to take back your work and brand/market it how you see fit. We’ve already given you back admin access to the repo, so you might transfer it to any account you like. @maelle can help with this process if necessary (Please note that you’ll have to transfer it to an account with a fork of the repository; in the past, we’ve noticed we could only transfer from an org to an individual and then from the individual to the org as opposed to from one org to another org directly, but the docs say differently now so this might not be a problem for you)

> First and foremost, the platform removes much of the brand recognition I need to keep my consulting business going.

rOpenSci is a community of practice for researchers who also develop software. Our mission is to foster a community of peers (especially for those who feel isolated in their institutions), and curate best practices, raise visibility, and credibility through peer review. Many researchers have benefited from the association with rOpenSci in various ways. These include success in grants, promotions, and leveraging their work here to establish a business or transition to an industry career. The relationship with rOpenSci is not meant to be static. Some developers move institutions, change careers/programming languages, and have no further interest in maintaining the package or participating in our community. In those cases, we help them find replacement maintainers or carefully archive the package and its assets.  Others like you are already established and see it best to brand all work under a single umbrella.  That is also totally fine.

> When promotion, community building, and maintenance remains largely the responsibility of “The Maintainer”, while brand recognition and bolstering of a growing ecosystem of packages can only be leveraged at scale by rOpenSci itself I start to question the platform’s business model.

As a non-profit, we raise support through grants for various programs. We are currently funded to build and operate the r-universe, create and administer a champions program for developers from underrepresented regions, and operationalize standards for statistical software peer review. So our business model is developing programs and infrastructure for the open-source scientific community.

We also regularly promote packages, build their documentation/binaries, help grow community, and ease the maintenance burden by surfacing issues, helping locate new maintainers, and more.

> I recognize that many contributors are academics for which the “potential” reduced overhead by handing things over to rOpenSci makes sense, as they have other sources of income. However, this equation changes dramatically if part of your income comes from brand recognition of your code work. This dynamic, IMO, does a disservice to small time developers of niche packages once stepping outside the academic sphere.

Participation is completely voluntary without any lock-in of any kind. If being part of this community is no longer helpful, you are welcome to make a decision that best serves you. We expect that people will stay as long as they get some benefit (which can take various forms). If you are past the point of getting any benefit, we fully support your decision to move all assets and brand associations to your business. No one is stopping you (or anyone else for that matter).

We wish you the best with your consulting business and would be happy to welcome you back in the future if you so decide.


Karthik & Maëlle

**Comment by khufkens** [comment]
Hi Karthik & Maelle,

Thanks for understanding my position, and business decision. 

I'll continue to contribute where I can to packages (rOpenSci or otherwise), time and expertise permitting.

I'll see to the transfer tomorrow.

Koen

**Comment by jeroen** [comment]
@khufkens Thanks for starting this discussion. I am interested in your opinion about the following, not only for MODISTools but also in general.

Do you think it would be more appealing for professional developers if R packages can become part of the rOpenSci ecosystem, whilst the package git repository remains be under your personal ownership (`https://github.com/khufkens/`)?

In practice this would mean that your package is automatically tracked and published on https://ropensci.r-universe.dev and https://docs.ropensci.org/MODISTools (w/ ropensci theme), but otherwise still remains completely under your own control.  Hence the situation is a bit comparable to publishing a package on CRAN: they host a copy of your package + binaries + docs (pdf manual, vignettes), without custom branding, that makes the package easily to find and install without otherwise imposing any restrictions.

Some historical context: in the past, the only sensible way for us to provide package maintainers with support, CI, and quality control was to maintain a single github organisation with all of our packages. However, more recently we have converted the build infrastructure and quality monitoring to https://ropensci.r-universe.dev, and https://docs.ropensci.org, which does not require to own the underlying git repositories anymore.

In fact, one of the use cases of r-universe is precisely that we (or anyone else) can maintain/monitor a dedicated repository with a curated set of R packages, without needing ownership of those packages. The packages may exist anywhere on git, and can be added to the suite, simply by including the url in our registry. Maybe this can be an option for package authors to participate in rOpenSci without feeling restricted.

**Comment by khufkens** [comment]
Hi Jeroen,

Yes, for sure. For two reasons, first business recognition and second intrinsic motivation (in general).

The first if fairly obvious, but let me expand on the second. If a package is fairly mature (with little true development) it is less likely to gather new maintainers or developers (as there is little need for true development). I think that the value of community support is there, but this certainly does not cover all packages (and depends on the kind and development status). Especially niche packages which are mature and with a well defined use case will be left out. 

In those cases, what maintainers are left with is the bureaucratic procedural work such as seeing to it that unit tests work, CRAN compliance stays up to date etc. This is an absolute time sink (money for professionals), and soul crushing if you don't have enough intrinsic motivation. 

As such, removing branding doesn't only have clear business side but also a psychological component, where removal of *perceived* ownership might remove a lot of intrinsic motivation. It does for me anyway. Or as I put in my Mastodon post.

> FOSS, in absence of a large community supporting a package developer, needs visibility (clear ownership) to maintain intrinsic motivation. If not, what was rewarding work will just become an unpaid job and the task to be abandoned.

So, to repeat, YES I think this a lot of value for those who want to build a business or are left out of the community just because of the cycle or scope of certain packages (niche, mature, general low maintenance ...)
