### ISSUE TITLE
mt_to_terra reproject does not work as expected

### ISSUE THREAD

**Issue by TheSl0thzilla** [khufkens/MODISTools#51]
When using reproject = T, which transfers to 4326 the image is still slanted, with no square pixels as I would expect after a reproject. 
I compared the results obtained by the former MRT tool (now HEG) and I guess it might by an issue with the underlying terra::project not recognising the sinusoidal projection correctly?

**Comment by maelle** [comment]
This package is now maintained at https://github.com/bluegreen-labs/MODISTools/ cc @khufkens
