### ISSUE TITLE
MODIS MCD15A2H product version?

### ISSUE THREAD

**Issue by stineb** [khufkens/MODISTools#52]
MODIS MCD15A2H v6 (e.g., LAI and FPAR) has been superseded by v6.1 ([link](https://lpdaac.usgs.gov/products/mcd15a2hv006/)). What version is downloaded by MODISTools? 

Can version number info be included in the `mt_products()` output?

**Comment by maelle** [comment]
This package is now maintained at https://github.com/bluegreen-labs/MODISTools/ cc @khufkens
