### ISSUE TITLE
mt_subset: Request failed [ERROR]

### ISSUE THREAD

**Issue by shevelp** [khufkens/MODISTools#53]
Hi all!

Several weeks ago, I downloaded data using the package: MOD13Q1 product and the 250m_16_days_NDVI band. I checked for data availability for my area and dates of interest, and there were no issues.

However, I've tried to download other bands for the same dates, such as 250m_16_days_VI_Quality, and I'm encountering an error during the download. I attempted to download the NDVI band again to see if the issue was with the VI band, but now it's also failing.

Below is the code I'm using:

```r
long_CENES=-3.51923;lat_CENES= 37.16184           #CENES
Lon_AB_BAJO= -3.44430;lat_AB_BAJO= 37.19939       #RAGUASBLANCAS_BAJO
LON_AB_ALTO= -3.39416;lat_AB_ALTO= 37.23146       #AGUAS BLANCAS ALTO
lon_GENIL_SALTO=-3.29243;lat_GENIL_SALTO=37.15791 #GENIL_SUPERALTO

products <- mt_products()
bands <- mt_bands(product = "MOD13Q1"); bands
dates <-mt_dates("MOD13Q1",lat = lat_CENES, lon = long_CENES)

# Descarga de productos 
TDF_Type <- mt_subset(product = "MOD13Q1", lat = lat_CENES, lon = long_CENES, 
                      band = "250m_16_days_NDVI", start = '2000-02-18', 
                      end = "2024-05-08", km_lr = 5, km_ab = 5, site_name = "CENES", 
                      internal = TRUE, progress = FALSE)
````

Error msg:
```
Request failed [ERROR]. Retrying in 1.8 seconds...
Request failed [502]. Retrying in 1.8 seconds...
Request failed [502]. Retrying in 2 seconds...
Request failed [504]. Retrying in 1.4 seconds...
Request failed [504]. Retrying in 1.4 seconds...
```
I'm unsure if it's a problem with the API or if it's something I might be doing incorrectly.

Thanks in advance!

**Comment by maelle** [comment]
This package is now maintained at https://github.com/bluegreen-labs/MODISTools/ cc @khufkens
